import AuthLayout from "@/components/layout/AuthLayout";
import React from "react";

const VolunteerTerms = () => {
  return (
    <AuthLayout hideScroll maxWidth="999px"> 

    <h1 className="text-3xl font-bold  text-center">Volunteer Declaration</h1>

  <div className="space-y-6">
        <section>
          <h2 className="text-xl font-semibold mb-2">Commitment to Volunteering</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>I understand the scope of the activities and responsibilities as a volunteer.</li>
            <li>I acknowledge that volunteering does not imply any full-time or part-time employment.</li>
            <li>I am committed to contributing my skills, services, and time as per the responsibilities assigned.</li>
            <li>I will abide by the rules, regulations, and procedures set by the Company.</li>
            <li>I understand that volunteer allowance will be based on the total number of leads generated by me during my volunteering activities.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Background & Disclosures</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>I have never been convicted of any crime.</li>
            <li>There are no pending litigations, inquiries, or complaints against me.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Consent</h2>
          <p>
            I voluntarily, explicitly, and unambiguously consent to the collection, use, retention, and transfer of my personal data by the Company
            for the exclusive purpose of managing and administering my volunteering activities. I understand that my data may be shared with third
            parties involved in these processes, and I consent to such sharing.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Final Acknowledgement</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>I have read and understood this declaration form completely.</li>
            <li>All the information I have provided is true and voluntary.</li>
            <li>This information is for verification purposes only.</li>
            <li>Providing false or misleading information may result in termination of my volunteering with the Company.</li>
          </ul>
        </section>
      </div>
      </AuthLayout>
  );
};

export default VolunteerTerms;
